name: build branch

on:
  push:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
