name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Create tag and release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - id: release
        name: Get next app version
        uses: rymndhng/release-on-push-action@master
        with:
          dry_run: true
          bump_version_scheme: minor
          tag_prefix: ""
      - name: Update app version
        uses: borales/actions-yarn@v4
        with:
          cmd: version --new-version ${{ steps.release.outputs.version }}
        env:
          YARN_VERSION_GIT_TAG: ""
      - name: Commit version
        run: >
          git config user.name "github-actions[bot]"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add package.json

          git commit -m "[AUTO] Release version ${{ steps.release.outputs.version }}"

          git push origin master

          git tag v${{ steps.release.outputs.version }}

          git push origin v${{ steps.release.outputs.version }}

      - name: Create release in github
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.release.outputs.version }}"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Create bundle
        run: >
          mkdir -p build && tar -czf build/back-home-build-${{ steps.release.outputs.version }}.tar.gz --exclude build .
      - name: Attach bundle into release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: build/back-home-build-${{ steps.release.outputs.version }}.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ steps.release.outputs.version }}
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "app": "back-home", "version" : "${{ steps.release.outputs.version }}"
            }'
  down-merge:
    needs: release
    name: Down merge
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Merge master -> develop
        run: >
          git config user.name "github-actions[bot]"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git merge origin/master

          git push origin develop
